#!/bin/bash                   

GREEN=$'\e[32m'
WHITE=$'\e[37m'

#   banner()
banner() {
echo $GREEN
echo ""
echo "********"
echo "* $1"
echo "********"
echo $WHITE
}

#  unmap/map )
dpdk_unbind_bind() {
echo "dpdk-devbind.py -u  $1"
dpdk-devbind.py -u  $1
echo "dpdk-devbind.py --bind=vfio-pci  $1"
dpdk-devbind.py --bind=vfio-pci  $1
}

#//////////////////////////////////

banner "Network "
dpdk_unbind_bind "0002:04:00.0";
dpdk_unbind_bind "0002:05:00.0";


banner "event dev  (SSO) "
dpdk_unbind_bind "0002:0e:00.0";


banner "mempool  (fpa) "
dpdk_unbind_bind "0002:0d:00.0";
# dpdk_unbind_bind "0002:0f:00.0";



banner "crypto "
dpdk_unbind_bind "0002:10:00.0";



